DROP DATABASE IF EXISTS FlowOverStack;
CREATE DATABASE IF NOT EXISTS FlowOverStack;
USE FlowOverStack;

DROP TABLE IF EXISTS QUESTIONS;

CREATE TABLE QUESTIONS (
	QuestionID		INT 	 		NOT NULL AUTO_INCREMENT,
	Title 			VARCHAR(200)	NOT NULL,
	Description		VARCHAR(2000)	NULL,
	CONSTRAINT		QUESTIONS_PK 	PRIMARY KEY(QuestionID)
);
	
DROP TABLE IF EXISTS ANSWER;

CREATE TABLE ANSWERS (
	AnswerID		INT 	 				NOT NULL AUTO_INCREMENT,
	QuestionID		INT						NOT NULL,
	Answer			VARCHAR(2000)			NOT NULL,
	CONSTRAINT		ANSWERS_PK 				PRIMARY KEY(AnswerID),
	CONSTRAINT 		ANSWERS_QUESTIONS_FK	FOREIGN KEY(QuestionID)
											REFERENCES QUESTIONS(QuestionID)
											ON UPDATE RESTRICT
											ON DELETE RESTRICT
);

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
	UserID			INT 			NOT NULL AUTO_INCREMENT,
	EmailAddress	VARCHAR(100)	NOT NULL,
	UserName		CHAR(25)		NOT NULL,
	Password		VARCHAR(50)		NOT NULL,
	CONSTRAINT 		USERS_PK 		PRIMARY KEY(UserID),
	CONSTRAINT 		USERS_EMAIL 	UNIQUE(EmailAddress)
);

DROP TABLE IF EXISTS FEEDBACK;

CREATE TABLE FEEDBACK (
	MessageID		INT 			NOT NULL AUTO_INCREMENT,
	Message			VARCHAR(2000)	NOT NULL,
	CONSTRAINT 		FEEDBACK_PK 	PRIMARY KEY(MessageID)
);

